on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-aarch64:
    name: aarch64_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1    
    - name: Arm64 test case
      run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
           arm64v8/ubuntu:latest \
           bash -exc 'apt-get update && apt-get -y install maven && \
           uname -m && \
           mvn clean install && \
           ls platforms/thorntail/api/target'
    - name: copy jar
      run: cp -r platforms/thorntail/api/target target/
    - name: Prepare
      id: prepare
      run: |
            TAG=${GITHUB_REF##*/}
            echo ::set-output name=tag_name::${TAG}
    - name: checking
      run: ls target/
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #- name: Login do docker.io
      #run: docker login -u abhishek138 -p ${{ secrets.DOCKER_TOKEN }}
    - name: build and publish image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          file: ./platforms/thorntail/api/Dockerfile 
          context: ./platforms/thorntail/api
          platforms: linux/arm64
          push: true
          tags: |
            abhishek138/team:${{ steps.prepare.outputs.tag_name }}
            abhishek138/team:latest


