name: Verify Build Workflow
on:
  push:
    paths-ignore:
      #- '.github/**'
      #- '.gitignore'
      #- 'LICENSE'
      - 'README*'
      #- 'CODE_OF_CONDUCT*'
    branches: [master]
  #pull_request:
   # paths-ignore:
    #  - '.github/**'
     # - '.gitignore'
      #- 'LICENSE'
      #- 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [master]

jobs:
  build-verify:
    name: Verify Build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64
      - name: Build Project
        run: mvn clean install
      #- name: Run Integration Tests
      #  run: mvn install -pl :apicurio-studio-test-integration-arquillian -Pintegration
      
